name: Fetch secrets from Vault
on:
  push:
    branches:
      - main
jobs:
  fetchSecrets:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Vault using JWT
        uses: hashicorp/vault-action@v2
        with:
          url: https://34.234.78.151:8200
          method: jwt
          role: my-github-role
          caCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZKVENDQXcyZ0F3SUJBZ0lVZGIxL3NnRGxPMzQzQklleWFub3FQdlQybmQwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF3d0piRzlqWVd4b2IzTjBNQjRYRFRJMU1EUXdNekExTXpJd01Gb1hEVEkyTURRdwpNekExTXpJd01Gb3dGREVTTUJBR0ExVUVBd3dKYkc5allXeG9iM04wTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBZzhBTUlJQ0NnS0NBZ0VBc1AvWWxzdlpuNkdaOHFmaHdENU54cDE4b1hTQVpQZThWTDdNdFNNbjJvOGMKRHFUdCszU3lhempPa2Y1RHU3WGZ4WTI3dGJ3U21udjhiVG9jUWM4Z3VrM2kxd0JKR1NudzFEZnQ5VENtaE9BcgorV0ROWExBbGQ0a3dPd3FndllxRDg3MjlSci9JT3g2cDlLOTd0T1IxL0V4VVU5SjV1T0pFNDl2TkhUVjY4eUErCnEvbjVZS1JOTmNNWVpWdFN6Z3l0RUk1L3BGZjhDNmdiOG9YQ1JmZkdibXdTN0Y1Wk5LSzBSem4yajR5ck9rS1AKRU9aSTlBWFREWUFuMTJZWUtzSXFad0pzWFlQZTYvZ0xjVEkvWFE1WXJRd25ZMDBQVXRya1FTTk02MUZTek1RbgpPeUhUdGlaNERhL3ZmaEgxSlI1ZTdpelFTTmFNQy95dklYeXc2Qi9OK0I5a2lZbXVpSkNGLzczV0E0OWNKMG1jCjVQWDdScTRXakR6TW8wbUpWQXVrTXE2SGt1ZCtBdElKRWhqVmxBQzV2WnlKK3BZcEFGT2xkNzVRMms0SnRQRjIKeW5MVzd0NDQyWUM0Q2JJVGNWVWNxTGwwRlVJcWFoRm4wWC9lSGMvWTFBRlROOWtTMWsrZXBuVlQ0Q1RkZ2tjcQorQTR1cWVmTjlRei85WXM3d3laUHNCWlZubXNkZWg1WUlqV203cWdZTWpDenIydzFTNmV4WnRGV1R4UlJrVC96CnJnVk05cktWek14eU5PdW4yVVNyWXVNNHVHY2l4dWdwcEs0bE9rZnJXUyt3QTB2TlRqK2NlaFlxTDVWYzJaYWgKaGZ6MjBMOEZ6RnhqalgvVEozb2JsakkrK0g2dGlKSzV1QjlDOXRsdFErWXJnTnF1czZTSjNHTlZnRGxUeHY4QwpBd0VBQWFOdk1HMHdIUVlEVlIwT0JCWUVGSlZHM3hSd3pIZ1JIcHVuYmRXN2dPUzIrQVlnTUI4R0ExVWRJd1FZCk1CYUFGSlZHM3hSd3pIZ1JIcHVuYmRXN2dPUzIrQVlnTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3R2dZRFZSMFIKQkJNd0VZSUpiRzlqWVd4b2IzTjBod1FBQUFBQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQ2o5VXRueGpWTQpVeWRoR0tiNG02MGpLM0dWRzQxbWU3Q1V3R3MxRlFTd21hMWdVdlNBdXdHWTY5U0FiQng3dWFRUG4vejZnRnNoClkwMDRLbzRhdjlUSUlwNFduU2h2cE0vUkxaTDMxSm1IN0NncU9MbU1nMHBZb2lpV001SzNqSHRVdCtJY0tDYXIKT3pJMlorMTJtaFBJdkYyMGsrSnpYcnEvVnRuMXlCaTVnYzJTMW00N1R1OGFvaUNZTWpiMzVLRzZOMk81U2xhSwpvMEFBbGszL1FheGhURGZUczd0L3c2ckpNZmxjeUhwa2pwLzY0VWNHT1ZtblZhUDk0cEZlT3pjb1k1VEFnb3BJCjRCNlVqdGJqSnRlMXZ0RVd5Z1RFMnJ3eGVEZndUaThYMzdtdWNLUVprNS9wM2VyQmtXODJrQ0NiY2MxamhKWHYKeDNtcGRvMXJnWVhYNlN4OExvWUpVdU4xMDkzOHdYMjF4T1NhQWMzei9BYjBmK3lZcGdBRGNiRFkvcU5DVWFVUAo1YVFTeitsN2NYZmZmRVdvbFNBOStYZmo3M21KdjIzeDdHVnZvNmMzS3NVMEMrYjNlQ0NPNWRoZE9KbGtRMHNrCnl3ZGJlOGY0ODZsSnYyU2p3dlVkVGV0Y2pyWHk2QlFkNnVaRGZCVTd2ZS9QYndRQi9xeXV4VFhrVms1OXhVZUMKZDE4S1pzNFBHMGNtS2pqVS9wNXlKRjVIYTY0Sk8yenhIYjRFQWUrQTBVM0N2WjVUT1lrcmVkVmFQWE4rdGdGZApjTGZCRktLUUt4K2w1bEdPVndjKzNWLzlHK3RCalFLSldsUEdHWXZ2TVJVY0ZZWjVKZW9ocmFOV0ZhdjNyQjIvCnRmSFRyVWJQQ2NpcmZGMmpUWFFjWlJVdEhkamFhNHcxVHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          secrets: |
            kv/data/sre-secrets SreSecret1 | SRE_SECRET_1 ;
            kv/data/sre-secrets SreSecret2 | SRE_SECRET_2

      - name: Read secret
        run: |
          echo "Fetching secret..."
          echo "SRE_SECRET_1: ${{ env.SRE_SECRET_1 }}""
          echo "SRE_SECRET_2: ${{ env.SRE_SECRET_2 }}""
          # Here you can add commands to fetch and use the secret
