name: Fetch secrets from Vault
on:
  push:
    branches:
      - main
jobs:
  fetchSecrets:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get OIDC Token
        id: get-token
        run: |
          OIDC_TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value')
          # echo "::add-mask::$OIDC_TOKEN"
          echo "token=$OIDC_TOKEN" >> $GITHUB_OUTPUT
          TOKEN="${{ steps.get-token.outputs.token }}"
          RESPONSE=$(curl -s -H "Authorization: Bearer $TOKEN" \
                   "http://34.234.78.151:5000/checkout?key=test_secret")
          
          # Show response (but mask any sensitive data)
          echo "Response from server:"
          echo "$RESPONSE"
          
      - name: Login to Vault using JWT
        uses: hashicorp/vault-action@v2
        with:
          url: https://34.234.78.151:8200
          method: jwt
          role: my-github-role
          tlsSkipVerify: true
          # caCertificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZKVENDQXcyZ0F3SUJBZ0lVWExvdTVaTnY4MHRzOE9paHNaVEFETW05RUFjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF3d0piRzlqWVd4b2IzTjBNQjRYRFRJMU1EUXdOREE0TVRBMU1Gb1hEVEkyTURRdwpOREE0TVRBMU1Gb3dGREVTTUJBR0ExVUVBd3dKYkc5allXeG9iM04wTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBZzhBTUlJQ0NnS0NBZ0VBc0dBZGpmcTFGL0NWN0JBd1VHTDVESXdsWkpteVVPQllNUmVSblE2UDJEVWwKc0h0aFFlMmZ0ZXN3WnhuVzhjdGxJQVRETUhPNGNOcEMrdFdZcDVjL3FWalJnNWRGb2VGQXRCc1Y5VTJ2dStwWgpkNWU0ODhsTjN6NlNwRlZMZjk3WnBUMTZyY1FEUmtJc2hYMC9HblJnbDdiRWRkQUh4WHVtUHNubTJuTGtKSFJRCnkxb3lrdUw3Uk10SEk1a0JucU1TWDVwazRXNndoQ0hLVXJKb21yVS81bkZNVEttQXROOXJOa2JkYWFKZyt2d2cKcnNWak5Icm1uTVR6eFR1UDdwRDU0aTBBL2FCOE9xWnF6d0lrdG1aWldVZFhTRWpGaEFEbXNpWXlCL3kvZ3dPNApmcStxeS82cjVvNENyc0xiTjhqZ2drOHVGSzNSczZWclZTdDgwOWxRSWZDc2VFT09jNzArZmVsb093a29qWmdUClZuZlB0STBYUGErYUV5NEF3Tlp2Nkl5QW5tVTgzQlRVYlk0WUwySUNvS2EyOCtoVXFzL3V0Y1dNcXFZczNaZm0KM1BXRWlIUnJTdTN4Snp1bkJPelFIekp3dmJaY3p5THpEcncvSjhyamNZMXFxVkZnTXVFbkFLZHNtVFZiWEF2MgpFblRuSE1GWnl6QVBwSlhyNklKV0YxWUxJSndVd1UzLzhMUXBpZCtqNDVJOThiV3NEcVpuV2JDR1RqQ2N0Y2h4CkdmdXNydmMvLzBqOHJxZ1V3bUdvc1ZVdDBrRWE0WjdwZ1lrUFg0NUM5V1ZTSUxyczk3bXNjNWZkOGl1VnpoR1YKOXJxNU5tZHhrMisxY2NCWDNpSkphdEpOMXljZVRQbVd3V3dKajZ5eWowdWZXUEExN1VSYU91amxGVFF6SXBzQwpBd0VBQWFOdk1HMHdIUVlEVlIwT0JCWUVGSnYyaVVYVmN4N2JjVVY4UjFoamI1eXZyNlkvTUI4R0ExVWRJd1FZCk1CYUFGSnYyaVVYVmN4N2JjVVY4UjFoamI1eXZyNlkvTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3R2dZRFZSMFIKQkJNd0VZSUpiRzlqWVd4b2IzTjBod1FpNms2WE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQVJMQzNHVkVDZgpVclNWZFhNQzVuN2VFL3d2QkZMZ3hqd2JlcVNYVUpWQVNuUVlxMWlLTEpsUklyTmFET3VjM3Q1SkNwWU5ibFk0CkpoUS95djI0TkJYQVBkTTFBdWZWRU14dWNrcFFFT0k4UGlLSzg4NTFCNVB1a2gxMmRJdjhhTnZ1TDFTYnpHMGYKSFRSZ3F3ZXZPQjR4VTF3bmhXZ3hoSkJYZ0J4WVNNaFBOcktQZnFZRGttQ3pqR2NUTDdwWUJpMFZTYnpweHUwbgp4ZS9IdkFjMHhaVzdDYUJuQnYzSTJubjBxUzIrdzZRZXRNaHNwemZEdmd4aFlseXNSOUZlb3k5SThFbzRIUHVKCnlQTkVHcDVlZldJaVdOR1Z4YUI3b0J0eCtXOCtmdUVta2lKb293VGlEZ29yamExcU1JSVpFUHlqQW5CNWJzeUgKcTgyY3FUTUN4L05Ga2RMcjZ4Z2RLb3hwN2VkRnJnUjV2Y1Q3TUw0OEFTNlN4MVA2NTJvWGo4QUw5UmFoQjl0ZwpJaE5QQnA2TXdCL3F3QnErTjBLTTJ6S2hNZVY4OHJGVVorUkNHNzJoK001aUJYcExQWGgvUFpyaDBPd1YzYmh5ClRoRDRZSXlLdDZUMzFJQ1ZrSlpXWFhqWW1uRWFBcVZUdVljSGUvUjdJU2pENncyaWd1TUd0ZjExR3oyU0U4MW8KTkpJN3M0OE45RlQ1SjljQWxGTUxrTkphZGNEcXBmT3dkbWRRSEV5alB0UjZPS3NvODl4K3BGYVhDMXkzeEt2TApLNUdJRzF1ZVNjZStqbUJzTStoQWhmeXRPdkJHT1FRYzYyUUhFSXFJY2poVlZlcWxnUzBEcjdMbzlLVEVDTEFqCnIzL2IrVWdMRmJQbXJTSDdnR0FQR3hLKzNialhGNnNvUWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          secrets: |
            kv/data/sre-secrets SreSecret1 | SRE_SECRET_1 ;
            kv/data/sre-secrets SreSecret2 | SRE_SECRET_2
          jwtGithubAudience: api://AzureADTokenExchange

      - name: Read secret
        run: |
          echo "Fetching secret..."
          echo "SRE_SECRET_1: ${{ env.SRE_SECRET_1 }}""
          echo "SRE_SECRET_2: ${{ env.SRE_SECRET_2 }}""
          # Here you can add commands to fetch and use the secret
